import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/ui/layout/sidebar/Sidebar";
import Navbar from "@/ui/layout/navbar/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex overflow-hidden h-screen">
          {/* sidebar */}
          <div className="w-[200px] flex-col    bg-yellow-50 flex items-center">
            <Sidebar />
          </div>
          {/* main content */}
          <div className="flex-col flex-1">
            {/* navbar */}
            <div className="flex-1    bg-amber-200 w-full">
              <Navbar />
            </div>

            <main className="flex-1 h-screen  ">{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}
