import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {/* Optional: Display server-rendered date with hydration warning suppressed */}
        <time
          dateTime={new Date().toISOString()}
          suppressHydrationWarning
        >
         
        </time>

        {children}
      </body>
    </html>
  );
}
